version: '2' 

services: 

  watchtower: 
    image: containrrr/watchtower 
    container_name: watchtower
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
      - /root/.docker/config.json:/config.json 
    command: nginx-proxy nginx-proxy-le 
    
  nginx-proxy: 
   #image: jwilder/nginx-proxy 
    image: dannycarrera/nginx-proxy
    container_name: nginx-proxy 
    restart: always 
    ports: 
      - "80:80" 
      - "443:443" 
    volumes: 
      - conf:/etc/nginx/conf.d 
      - ./my_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf
      - vhost:/etc/nginx/vhost.d 
      - html:/usr/share/nginx/html 
      - dhparam:/etc/nginx/dhparam 
      - certs:/etc/nginx/certs:ro 
      - /var/run/docker.sock:/tmp/docker.sock:ro 

  letsencrypt: 
    image: jrcs/letsencrypt-nginx-proxy-companion 
    container_name: nginx-proxy-le 
    restart: always 
    environment: 
      - DEFAULT_EMAIL=certs@ne2k.in 
    # - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
    volumes_from: 
      - nginx-proxy 
    volumes: 
      - certs:/etc/nginx/certs:rw 
      - /var/run/docker.sock:/var/run/docker.sock:ro 

volumes: 
  conf: 
  vhost: 
  html: 
  dhparam: 
  certs: 

networks:
    default:
        external:
            name: service-network
